version: 2.1
orbs:
  ssh-deployment: arturgontijo/ssh-deployment@dev:0.0.1
jobs:
  service-1:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST}
          ssh-user: ${SSH_USER}
workflows:
  test-services:
    jobs:
      - service-1
