version: 2.1
orbs:
  ssh-deployment: arturgontijo/ssh-deployment@1.1.20
workflows:
  deploy_application:
    jobs:
      - ssh-deployment/deploy:
          ssh-host: 35.173.128.153
          ssh-user: ubuntu
          git-repo: ssh-circleci
          git-branch: master
          mainnet-port: '7000'
          run-command: docker build -t redis .
          test-command: docker build -t redis .
          docker-test-files: 'Dockerfile'
          docker-file-path: Dockerfile
          docker-image: redis
          docker-container: redis